"""Packs the Lucide icons the Stream Deck already ships into icons.js for the video."""
import json, re
from pathlib import Path
HERE = Path(__file__).resolve().parent.parent
SRC = HERE.parent.parent / 'agent' / 'streamdeck' / 'assets' / 'icons'
names = ['Mic', 'Mail', 'Pencil', 'Play', 'Send', 'Volume2', 'Languages', 'Gamepad2', 'Dog', 'Cat',
         'Rabbit', 'Fish', 'Bird', 'Home', 'Check', 'Palette', 'HelpCircle', 'RotateCcw', 'Users', 'Clock', 'Umbrella']
icons = {}
for n in names:
    svg = (SRC / f'{n}.svg').read_text()
    icons[n] = re.sub(r'^.*?<svg[^>]*>|</svg>\s*$', '', svg, flags=re.S)
(HERE / 'icons.js').write_text('// Generated by scripts/make_icons.py from agent/streamdeck/assets/icons (Lucide, ISC).\nwindow.ICONS = ' + json.dumps(icons, indent=1) + ';\n')
print(len(icons))
